//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProcat.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<System.DateTime> ImageDate { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual luStatu luStatu { get; set; }
        public virtual PersonalDetail PersonalDetail { get; set; }
        public virtual User1 User1 { get; set; }
    }
}
