//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProcat.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class luDocumentType1
    {
        public int Id { get; set; }
        public string DocumentDescription { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
