//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProcat.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public int PatientId { get; set; }
        public string Message { get; set; }
        public string MobileNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int StatusID { get; set; }
    
        public virtual luStatu luStatu { get; set; }
        public virtual PersonalDetail PersonalDetail { get; set; }
    }
}
