//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProcat.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonalDetail()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Documents = new HashSet<Document>();
            this.NextOfKins = new HashSet<NextOfKin>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Surname { get; set; }
        public string IdNumber { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNumber { get; set; }
        public string WorkTelNumber { get; set; }
        public string HomeTelNumber { get; set; }
        public string Employer { get; set; }
        public string EmployerContactPerson { get; set; }
        public string EmployerTelNumber { get; set; }
        public string EmployerEmailAddress { get; set; }
        public Nullable<int> NumberofDependants { get; set; }
        public string Photo { get; set; }
        public Nullable<int> MedicalAidId { get; set; }
        public Nullable<int> PatientTypeId { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public int StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual luGender luGender { get; set; }
        public virtual luMaritalStatu luMaritalStatu { get; set; }
        public virtual luMedicalAid luMedicalAid { get; set; }
        public virtual luStatu luStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NextOfKin> NextOfKins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
