//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProcat.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class prac_practice
    {
        public string PracticeNumber { get; set; }
        public string PracDescription { get; set; }
        public string PracAddress { get; set; }
        public string PracOfficeNum { get; set; }
        public string PracEmailAddress { get; set; }
    }
}
