//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProcat.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_PracticeUser
    {
        public string PracticeNumber { get; set; }
        public string IDNumber { get; set; }
        public bool PracStatus { get; set; }
    }
}
