//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProcat.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Procat3Entities : DbContext
    {
        public Procat3Entities()
            : base("name=Procat3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<luDocumentType> luDocumentTypes { get; set; }
        public virtual DbSet<luGender> luGenders { get; set; }
        public virtual DbSet<luMaritalStatu> luMaritalStatus { get; set; }
        public virtual DbSet<luMedicalAid> luMedicalAids { get; set; }
        public virtual DbSet<luStatu> luStatus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<NextOfKin> NextOfKins { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<PersonalDetail> PersonalDetails { get; set; }
        public virtual DbSet<PracticeDetail> PracticeDetails { get; set; }
        public virtual DbSet<prac_practice> prac_practice { get; set; }
        public virtual DbSet<prc_PracticeUser> prc_PracticeUser { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<luHomeEnvironment> luHomeEnvironments { get; set; }
        public virtual DbSet<luMobilityGrade> luMobilityGrades { get; set; }
        public virtual DbSet<luProsthesisDailyDuration> luProsthesisDailyDurations { get; set; }
        public virtual DbSet<luProsthesisFrequency> luProsthesisFrequencies { get; set; }
        public virtual DbSet<luQueue> luQueues { get; set; }
        public virtual DbSet<luTransport> luTransports { get; set; }
        public virtual DbSet<luWeight> luWeights { get; set; }
        public virtual DbSet<luWorkEnvironment> luWorkEnvironments { get; set; }
        public virtual DbSet<luRole> luRoles { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
        public virtual DbSet<luDocumentType1> luDocumentType1 { get; set; }
    }
}
